import type { SiteLanguage } from './siteLanguage';

export type BusinessDesignId = 'meridian' | 'forma' | 'verde' | 'studio';
export type BusinessSection = 'home' | 'collection' | 'about' | 'journal' | 'contact' | 'item' | 'bag';
type Text = [string, string, string];
export const bt = (text: Text, language: SiteLanguage) => text[language === 'uk' ? 1 : language === 'ro' ? 2 : 0];
export type BusinessItem = { id: string; title: Text; category: number; image: string; description: Text; price?: number };
export type BusinessDesign = {
  brand: string; signature: Text; title: Text; intro: Text; collection: Text; aboutTitle: Text; about: Text;
  hero: string; categories: Text[]; items: BusinessItem[]; stats: [string, Text][]; journal: { title: Text; text: Text; image: string }[];
};
const image = (name: string) => `/images/business-demos/${name}.webp`;
export const businessDemos: Record<BusinessDesignId, BusinessDesign> = {
  meridian: {
    brand: 'MERIDIAN', signature: ['INDEPENDENT BUSINESS ADVISORY', 'НЕЗАЛЕЖНИЙ БІЗНЕС-КОНСАЛТИНГ', 'CONSULTANȚĂ INDEPENDENTĂ'],
    title: ['A clear direction.\nA stronger business.', 'Чіткий напрям.\nСильніший бізнес.', 'O direcție clară.\nO afacere mai puternică.'],
    intro: ['We turn complex decisions into confident next steps. Strategy, operations and finance — working together.', 'Перетворюємо складні рішення на впевнені кроки. Стратегія, операції та фінанси працюють разом.', 'Transformăm deciziile complexe în pași siguri. Strategie, operațiuni și finanțe, împreună.'],
    collection: ['Our expertise', 'Наша експертиза', 'Expertiza noastră'], hero: image('building'),
    aboutTitle: ['Good advice starts\nwith listening.', 'Хороша порада\nпочинається з уваги.', 'Un sfat bun începe\ncu ascultarea.'],
    about: ['An independent advisory practice built around people, not presentations. Our multidisciplinary team works alongside founders and leaders to build resilient companies. Every engagement begins with the right questions and ends with a practical plan.', 'Незалежна консалтингова компанія, що працює з людьми. Наша команда допомагає засновникам і керівникам будувати стійкий бізнес. Починаємо з правильних запитань і завершуємо практичним планом.', 'O companie independentă construită în jurul oamenilor. Echipa noastră lucrează alături de fondatori pentru afaceri rezistente. Începem cu întrebările potrivite și încheiem cu un plan practic.'],
    categories: [['All expertise', 'Усі напрями', 'Toată expertiza'], ['Strategy', 'Стратегія', 'Strategie'], ['Operations', 'Операції', 'Operațiuni'], ['Finance', 'Фінанси', 'Finanțe']],
    items: [
      { id: 'growth-strategy', category: 1, image: image('office'), title: ['Growth strategy', 'Стратегія зростання', 'Strategie de creștere'], description: ['A focused roadmap for your next chapter. Market research, positioning and a 90-day action plan, built with your leadership team.', 'Чіткий план наступного етапу: дослідження ринку, позиціювання та дії на 90 днів разом із вашою командою.', 'O foaie de parcurs clară: cercetare de piață, poziționare și un plan de acțiune de 90 de zile.'] },
      { id: 'operating-model', category: 2, image: image('meeting'), title: ['A better operating model', 'Ефективніша операційна модель', 'Un model operațional mai bun'], description: ['Simplify how your business works. We map processes, remove friction and help teams take ownership of meaningful outcomes.', 'Спрощуємо роботу бізнесу: аналізуємо процеси, прибираємо зайві кроки та визначаємо відповідальність команд.', 'Simplificăm procesele, eliminăm obstacolele și ajutăm echipele să își asume rezultate concrete.'] },
      { id: 'financial-clarity', category: 3, image: image('building'), title: ['Financial clarity', 'Фінансова ясність', 'Claritate financiară'], description: ['Understand the numbers behind your decisions. Scenario planning, cash-flow visibility and reporting that actually helps.', 'Цифри, що допомагають приймати рішення: сценарне планування, грошові потоки та зрозуміла звітність.', 'Înțelege cifrele din spatele deciziilor: scenarii, fluxuri de numerar și rapoarte utile.'] },
      { id: 'market-entry', category: 1, image: image('interior'), title: ['New market entry', 'Вихід на нові ринки', 'Intrare pe piețe noi'], description: ['Find your next opportunity. We evaluate demand, local partnerships and launch options before you invest.', 'Знаходимо наступну можливість: оцінюємо попит, місцевих партнерів та варіанти запуску до інвестицій.', 'Evaluăm cererea, parteneriatele și opțiunile de lansare înainte de investiție.'] },
    ],
    stats: [['12+', ['Years of perspective', 'Років досвіду', 'Ani de experiență']], ['38', ['Industries explored', 'Галузей досліджено', 'Industrii explorate']], ['01', ['Team on your side', 'Команда на вашому боці', 'Echipă alături de tine']]],
    journal: [{ title: ['The value of a simpler plan', 'Цінність простішого плану', 'Valoarea unui plan simplu'], text: ['Strategy becomes useful when people know what to do on Monday. Start with one measurable goal, agree on three priorities, and review progress every month. Clarity creates momentum.', 'Стратегія працює, коли команда знає, що робити в понеділок. Визначте вимірювану мету, три пріоритети та щомісячний огляд прогресу. Ясність створює рух.', 'Strategia este utilă când echipa știe ce să facă luni. O țintă măsurabilă, trei priorități și o revizuire lunară creează progres.'], image: image('office') }],
  },
  forma: {
    brand: 'forma /', signature: ['ARCHITECTURE & INTERIORS', 'АРХІТЕКТУРА ТА ІНТЕР’ЄРИ', 'ARHITECTURĂ & INTERIOARE'],
    title: ['Spaces for\nthe way we live.', 'Простір\nдля нашого життя.', 'Spații pentru\nfelul în care trăim.'],
    intro: ['Thoughtful architecture. Honest materials. Places that feel as good as they look.', 'Продумана архітектура. Чесні матеріали. Простір, у якому добре жити.', 'Arhitectură atentă. Materiale autentice. Locuri în care te simți bine.'], collection: ['Selected spaces', 'Обрані проєкти', 'Spații selectate'], hero: image('interior'),
    aboutTitle: ['Built around\nreal life.', 'Навколо\nсправжнього життя.', 'Construite în jurul\nvieții reale.'],
    about: ['We are a small architecture practice with a patient approach. From the first sketch to the final material, we consider light, rhythm and how a space will be used. Our work spans private homes, shared spaces and places to gather.', 'Ми невелика архітектурна студія з уважним підходом. Від першого ескізу до останнього матеріалу враховуємо світло, ритм і спосіб життя. Проєктуємо приватні будинки та громадські простори.', 'Suntem un birou mic cu o abordare atentă. De la prima schiță la ultimul material, luăm în considerare lumina și utilizarea spațiului. Proiectăm locuințe și spații comune.'],
    categories: [['All projects', 'Усі проєкти', 'Toate proiectele'], ['Residential', 'Житлові', 'Rezidențial'], ['Interiors', 'Інтер’єри', 'Interioare'], ['Workspaces', 'Робочі простори', 'Birouri']],
    items: [
      { id: 'quiet-residence', category: 1, image: image('house'), title: ['The quiet residence', 'Тиха резиденція', 'Reședința liniștită'], description: ['A family home shaped by natural light. An open plan connects shared rooms, while warm timber and stone create a grounded, quiet atmosphere. Concept project · 240 m².', 'Сімейний будинок, сформований природним світлом. Відкритий план, тепле дерево та камінь створюють спокійну атмосферу. Концепт · 240 м².', 'O casă de familie modelată de lumină. Plan deschis, lemn și piatră pentru o atmosferă calmă. Concept · 240 m².'] },
      { id: 'soft-interior', category: 2, image: image('interior'), title: ['A softer interior', 'М’який інтер’єр', 'Un interior mai blând'], description: ['A study in texture and restraint. Neutral finishes, carefully chosen furniture and generous breathing room bring an apartment back to the essentials. Concept project · 86 m².', 'Дослідження фактур і стриманості. Нейтральне оздоблення, продумані меблі та багато простору. Концепт · 86 м².', 'Texturi și simplitate. Finisaje neutre și mobilier atent ales într-un apartament aerisit. Concept · 86 m².'] },
      { id: 'open-studio', category: 3, image: image('office'), title: ['The open studio', 'Відкрита студія', 'Studioul deschis'], description: ['A workspace that makes room for people. Shared tables, quiet corners and plenty of daylight balance collaboration with focus. Concept project · 420 m².', 'Робочий простір для людей: спільні столи, тихі куточки та багато денного світла. Концепт · 420 м².', 'Un birou pentru oameni: mese comune, colțuri liniștite și multă lumină. Concept · 420 m².'] },
      { id: 'garden-room', category: 1, image: image('room'), title: ['The garden room', 'Кімната біля саду', 'Camera spre grădină'], description: ['A living space connected to its landscape. Soft light, tactile surfaces and natural tones blur the boundary between inside and outside. Concept project · 120 m².', 'Простір, пов’язаний із ландшафтом: м’яке світло, природні відтінки та тактильні поверхні. Концепт · 120 м².', 'Un spațiu legat de peisaj, cu lumină blândă și nuanțe naturale. Concept · 120 m².'] },
    ],
    stats: [['2014', ['Established', 'Рік заснування', 'Înființat']], ['24', ['Considered spaces', 'Продуманих просторів', 'Spații proiectate']], ['08', ['People, one practice', 'Людей, одна студія', 'Oameni, un birou']]],
    journal: [{ title: ['Let the light lead', 'Нехай світло веде', 'Lasă lumina să conducă'], text: ['Before choosing a material, we watch the light. How it enters in the morning, where it rests at noon, and what it leaves behind at dusk. A good room is a conversation between architecture and the day.', 'Перед вибором матеріалів ми спостерігаємо за світлом. Як воно входить уранці та змінюється ввечері. Хороша кімната — розмова між архітектурою та днем.', 'Înainte de materiale, privim lumina: dimineața, la prânz și la apus. O cameră bună este un dialog între arhitectură și zi.'], image: image('room') }],
  },
  verde: {
    brand: 'verde', signature: ['A LITTLE CLOSER TO NATURE', 'ТРОХИ БЛИЖЧЕ ДО ПРИРОДИ', 'PUȚIN MAI APROAPE DE NATURĂ'],
    title: ['Bring the\noutside in.', 'Запросіть\nприроду додому.', 'Adu natura\nîn casa ta.'],
    intro: ['Living greens and everyday essentials for a slower, softer home. Find your little piece of nature.', 'Живі рослини та прості речі для затишного дому. Знайдіть свій маленький куточок природи.', 'Plante vii și lucruri simple pentru o casă liniștită. Găsește colțul tău de natură.'], collection: ['The green collection', 'Зелена колекція', 'Colecția verde'], hero: image('ficus'),
    aboutTitle: ['Small things.\nA greener everyday.', 'Маленькі речі.\nЗеленіше щодня.', 'Lucruri mici.\nZile mai verzi.'],
    about: ['Verde began with a windowsill full of plants and a simple idea: nature belongs in everyday life. We select easy-going greens and objects made to last. Our fictional shop is a place to explore how a thoughtful collection comes together.', 'Verde почався з підвіконня, повного рослин, і простої ідеї: природа має бути поруч щодня. Ми обираємо невибагливу зелень і довговічні речі. Це демонстраційний магазин продуманої колекції.', 'Verde a început cu un pervaz plin de plante: natura aparține vieții de zi cu zi. Alegem plante ușor de îngrijit și obiecte durabile. Un magazin demonstrativ pentru o colecție atentă.'],
    categories: [['Everything', 'Усе', 'Totul'], ['Plants', 'Рослини', 'Plante'], ['Plant care', 'Догляд', 'Îngrijire'], ['For the home', 'Для дому', 'Pentru casă']],
    items: [
      { id: 'ficus', category: 1, image: image('ficus'), price: 32, title: ['Ficus elastica', 'Фікус еластика', 'Ficus elastica'], description: ['Big leaves, easy company. A statement plant for a bright corner. Indirect light · water weekly. Sample product, not available for purchase.', 'Великі листки, простий догляд. Рослина для світлого куточка. Розсіяне світло · полив щотижня. Демотовар.', 'Frunze mari, îngrijire simplă. Lumină indirectă · udare săptămânală. Produs demonstrativ.'] },
      { id: 'succulent', category: 1, image: image('planter'), price: 24, title: ['The little succulent', 'Маленький сукулент', 'Micul suculent'], description: ['A little green for your desk or shelf. A low-maintenance succulent in a mint ceramic pot. Bright indirect light · water when soil is dry. Sample product.', 'Трохи зелені для столу або полиці. Невибагливий сукулент у м’ятному горщику. Розсіяне світло · полив після висихання ґрунту. Демотовар.', 'O plantă pentru birou, în ghiveci ceramic mentă. Lumină indirectă · udare când solul e uscat. Produs demonstrativ.'] },
      { id: 'garden-kit', category: 2, image: image('plants'), price: 18, title: ['The plant care kit', 'Набір догляду за рослинами', 'Set de îngrijire'], description: ['A thoughtful kit for your growing collection. A hand trowel and compact pruning tools for everyday plant care. Sample product.', 'Продуманий набір для вашої колекції: ручна лопатка та компактні інструменти для догляду за рослинами. Демотовар.', 'Un set pentru colecția ta: lopățică și unelte compacte pentru îngrijire. Produs demonstrativ.'] },
      { id: 'quiet-corner', category: 3, image: image('room'), price: 48, title: ['A quiet corner print', 'Постер «Тихий куточок»', 'Print „Un colț liniștit”'], description: ['A botanical interior photograph, printed on textured paper. 30 × 40 cm · unframed · archival print. Sample product.', 'Фотографія інтер’єру на фактурному папері. 30 × 40 см · без рамки · архівний друк. Демотовар.', 'Fotografie de interior pe hârtie texturată. 30 × 40 cm · fără ramă. Produs demonstrativ.'] },
    ],
    stats: [['01', ['Thoughtful collection', 'Продумана колекція', 'Colecție atentă']], ['100%', ['A little more natural', 'Трохи природніше', 'Mai aproape de natură']], ['365', ['Days to grow', 'Днів для зростання', 'Zile de creștere']]],
    journal: [{ title: ['Your first green friend', 'Ваш перший зелений друг', 'Primul tău prieten verde'], text: ['Start with the light, not the plant. A bright room with indirect sun opens up plenty of options. Check the soil before watering, give leaves a gentle clean, and let your plant settle into its new home.', 'Почніть зі світла. Світла кімната без прямого сонця дає багато можливостей. Перевіряйте ґрунт перед поливом, очищуйте листя й дайте рослині звикнути до дому.', 'Începe cu lumina. O cameră luminoasă fără soare direct oferă multe opțiuni. Verifică solul, curăță frunzele și lasă planta să se acomodeze.'], image: image('ficus') }],
  },
  studio: {
    brand: 'STUDIO®', signature: ['INDEPENDENT CREATIVE COMPANY', 'НЕЗАЛЕЖНА КРЕАТИВНА КОМПАНІЯ', 'COMPANIE CREATIVĂ INDEPENDENTĂ'],
    title: ['GOOD IDEAS.\nGREAT IMPACT.', 'СИЛЬНІ ІДЕЇ.\nВЕЛИКИЙ ВПЛИВ.', 'IDEI BUNE.\nIMPACT MARE.'],
    intro: ['We build brands with a point of view. Strategy, identity and digital experiences for the next generation of business.', 'Створюємо бренди з власним поглядом. Стратегія, айдентика та цифровий досвід для нового покоління бізнесу.', 'Construim branduri cu personalitate. Strategie, identitate și experiențe digitale pentru noua generație de afaceri.'], collection: ['Work with a point of view', 'Роботи з власним поглядом', 'Proiecte cu personalitate'], hero: image('abstract'),
    aboutTitle: ['Serious about\nstanding out.', 'Серйозно\nпро виразність.', 'Serioși despre\na ieși în evidență.'],
    about: ['A small team with a big appetite for good ideas. We combine sharp strategy with expressive design to make brands people remember. We work across identity, campaigns and digital — from first conversation to final launch.', 'Невелика команда з великим апетитом до ідей. Поєднуємо чітку стратегію та виразний дизайн, щоб бренди запам’ятовувалися. Айдентика, кампанії та цифрові продукти — від розмови до запуску.', 'O echipă mică cu idei mari. Combinăm strategia cu designul expresiv pentru branduri memorabile. Identitate, campanii și produse digitale, de la conversație la lansare.'],
    categories: [['All work', 'Усі роботи', 'Toate proiectele'], ['Identity', 'Айдентика', 'Identitate'], ['Digital', 'Цифрові продукти', 'Digital'], ['Campaigns', 'Кампанії', 'Campanii']],
    items: [
      { id: 'objects-of-tomorrow', category: 1, image: image('abstract'), title: ['Objects of tomorrow', 'Об’єкти майбутнього', 'Obiectele de mâine'], description: ['An expressive identity for an imagined design brand. Bold colour, flexible typography and a system that moves from packaging to screen. Concept · strategy / identity / art direction.', 'Виразна айдентика уявного дизайн-бренду. Сміливий колір, гнучка типографіка та система для пакування й екранів. Концепт · стратегія / айдентика.', 'Identitate expresivă pentru un brand imaginar. Culoare, tipografie și un sistem flexibil. Concept · strategie / identitate.'] },
      { id: 'open-culture', category: 2, image: image('meeting'), title: ['Open culture', 'Відкрита культура', 'Cultură deschisă'], description: ['A digital home for a new creative community. An accessible editorial system, dynamic project archive and a clear path to joining the conversation. Concept · digital / experience.', 'Цифровий дім нової креативної спільноти. Доступна редакційна система, архів проєктів і зрозумілий шлях до спілкування. Концепт · цифровий досвід.', 'Un spațiu digital pentru o comunitate creativă: sistem editorial și arhivă de proiecte. Concept · experiență digitală.'] },
      { id: 'make-room', category: 3, image: image('room'), title: ['Make room for more', 'Місце для більшого', 'Loc pentru mai mult'], description: ['A campaign about the spaces we share. Photography-led storytelling and a distinctive graphic language for an imagined furniture company. Concept · campaign / content.', 'Кампанія про спільні простори. Візуальні історії та виразна графічна мова для уявної меблевої компанії. Концепт · кампанія / контент.', 'O campanie despre spațiile comune. Fotografie și limbaj grafic pentru o companie imaginară de mobilier. Concept · campanie.'] },
      { id: 'future-office', category: 2, image: image('office'), title: ['The future is open', 'Майбутнє відкрите', 'Viitorul e deschis'], description: ['A fresh web experience for a workplace brand. An intuitive service catalogue, strong editorial imagery and a confident brand voice. Concept · website / identity.', 'Новий вебдосвід бренду робочих просторів. Інтуїтивний каталог послуг, виразні зображення та впевнений голос. Концепт · сайт / айдентика.', 'O experiență web pentru spații de lucru: catalog intuitiv și imagini puternice. Concept · website / identitate.'] },
    ],
    stats: [['03', ['Disciplines, one team', 'Напрями, одна команда', 'Discipline, o echipă']], ['∞', ['Room for ideas', 'Простір для ідей', 'Spațiu pentru idei']], ['100%', ['Independent thinking', 'Незалежне мислення', 'Gândire independentă']]],
    journal: [{ title: ['A brand is a behaviour', 'Бренд — це поведінка', 'Un brand este un comportament'], text: ['A logo starts the conversation. What happens next matters more: the words you choose, the experience you create and the promises you keep. We design systems that connect all three.', 'Логотип починає розмову. Далі важливіші слова, досвід і виконані обіцянки. Ми проєктуємо системи, що поєднують ці три складники.', 'Logo-ul începe conversația. Contează cuvintele, experiența și promisiunile respectate. Proiectăm sisteme care le conectează.'], image: image('abstract') }],
  },
};

export const businessCopy = {
  home: ['Home', 'Головна', 'Acasă'], about: ['About us', 'Про нас', 'Despre noi'], journal: ['Journal', 'Журнал', 'Jurnal'], contact: ['Get in touch', 'Зв’язатися', 'Contact'],
  explore: ['Explore', 'Переглянути', 'Explorează'], more: ['Find out more', 'Дізнатися більше', 'Află mai mult'], all: ['View all', 'Переглянути все', 'Vezi tot'],
  story: ['Our story', 'Наша історія', 'Povestea noastră'], search: ['Search the collection', 'Пошук у колекції', 'Caută în colecție'], empty: ['No matches. Try another search.', 'Нічого не знайдено. Спробуйте інший запит.', 'Niciun rezultat. Încearcă altă căutare.'],
  reset: ['Reset filters', 'Скинути фільтри', 'Resetează filtrele'], found: ['results', 'результатів', 'rezultate'], back: ['Back to collection', 'Назад до колекції', 'Înapoi la colecție'],
  add: ['Add to bag', 'Додати до кошика', 'Adaugă în coș'], added: ['Added to your demo bag', 'Додано до демокошика', 'Adăugat în coșul demo'], bag: ['Your bag', 'Ваш кошик', 'Coșul tău'],
  emptyBag: ['Your bag is waiting for a little green.', 'Ваш кошик чекає на трохи зелені.', 'Coșul tău așteaptă puțină verdeață.'], remove: ['Remove', 'Видалити', 'Elimină'], total: ['Subtotal', 'Разом', 'Subtotal'],
  checkout: ['Try demo checkout', 'Спробувати демозамовлення', 'Încearcă comanda demo'], completed: ['Demo complete. No order or payment was created.', 'Демо завершено. Замовлення та оплату не створено.', 'Demo finalizat. Nu a fost creată nicio comandă sau plată.'],
  next: ['Next project', 'Наступний проєкт', 'Următorul proiect'], read: ['Read the article', 'Читати статтю', 'Citește articolul'],
  contactTitle: ['Let’s start a conversation.', 'Почнімо розмову.', 'Să începem o conversație.'], contactIntro: ['Tell us a little about what you have in mind.', 'Розкажіть трохи про вашу ідею.', 'Spune-ne câteva lucruri despre ideea ta.'],
  team: ['Different perspectives. Shared purpose.', 'Різні погляди. Спільна мета.', 'Perspective diferite. Scop comun.'],
  process: ['How we work', 'Як ми працюємо', 'Cum lucrăm'], steps: [['Listen', 'Слухаємо', 'Ascultăm'], ['Explore', 'Досліджуємо', 'Explorăm'], ['Make it happen', 'Втілюємо', 'Realizăm']],
  sample: ['Fictional business · Sample content', 'Вигаданий бізнес · Демоконтент', 'Afacere fictivă · Conținut demo'],
  details: ['The details', 'Деталі', 'Detalii'], question: ['Questions before you begin?', 'Маєте запитання?', 'Ai întrebări?'],
  faq: ['These are interactive design examples. Services, projects and products are sample content. The form and bag demonstrate the experience without sending information or accepting payment.', 'Це інтерактивні приклади дизайну. Послуги, проєкти та товари — демонстраційні. Форма й кошик показують роботу сайту без надсилання даних або приймання оплати.', 'Acestea sunt exemple interactive. Serviciile, proiectele și produsele sunt demonstrative. Formularul și coșul nu trimit informații și nu acceptă plăți.'],
} satisfies Record<string, Text | Text[]>;
