const copy = {
  en: {
    title: 'Tell us about your project', noAccount: 'No registration needed',
    description: 'A few words are enough. We will work out the details together.',
    services: 'What do you need?', website: 'Website development', websiteType: 'Website type',
    landing: 'Landing page', corporate: 'Business website', redesign: 'Website redesign',
    unsure: 'Help me choose', reply: 'Where should we reply?', replyPlaceholder: 'Email / Telegram / Instagram',
    replyAccount: 'Optional — we can reply through your account',
    business: 'Business website or social media (optional)', businessPlaceholder: 'Website or business profile link',
    businessHint: 'If you already have a business, share a link so we can get to know it.',
    commentPlaceholder: 'What do you do, and what would you like to achieve?',
    nextStep: 'We will review your request and contact you using the details you provide.',
    accountNextStep: 'We will review your request and reply through your account or the contact you provide.',
    optional: 'Optional details', estimate: 'Calculate a price estimate', base: 'Base example', applied: 'Estimate added to your request',
    next: 'Next: additional features', back: 'Back', apply: 'Add estimate to request',
    designs: 'Choose a design direction', allDesigns: 'All design directions',
  },
  uk: {
    title: 'Розкажіть про свій проєкт', noAccount: 'Без реєстрації',
    description: 'Достатньо кількох слів. Деталі обговоримо разом.',
    services: 'Що вам потрібно?', website: 'Розробка сайту', websiteType: 'Тип сайту',
    landing: 'Лендинг', corporate: 'Сайт для бізнесу', redesign: 'Редизайн сайту',
    unsure: 'Допоможіть обрати', reply: 'Куди вам відповісти?', replyPlaceholder: 'Email / Telegram / Instagram',
    replyAccount: 'Необов’язково — можемо відповісти в кабінеті',
    business: 'Сайт або соцмережі бізнесу (необов’язково)', businessPlaceholder: 'Посилання на сайт або профіль бізнесу',
    businessHint: 'Якщо у вас уже є бізнес, залиште посилання, щоб ми могли з ним познайомитися.',
    commentPlaceholder: 'Чим ви займаєтеся та якого результату хочете досягти?',
    nextStep: 'Переглянемо вашу заявку та зв’яжемося за вказаним контактом.',
    accountNextStep: 'Переглянемо заявку та відповімо в кабінеті або за вказаним контактом.',
    optional: 'Додаткові деталі', estimate: 'Розрахувати орієнтовну вартість', base: 'Базовий приклад', applied: 'Розрахунок додано до заявки',
    next: 'Далі: додаткові можливості', back: 'Назад', apply: 'Додати розрахунок до заявки',
    designs: 'Обрати напрям дизайну', allDesigns: 'Усі напрями дизайну',
  },
  ro: {
    title: 'Povestește-ne despre proiectul tău', noAccount: 'Fără înregistrare',
    description: 'Câteva cuvinte sunt suficiente. Vom discuta detaliile împreună.',
    services: 'De ce ai nevoie?', website: 'Dezvoltare site', websiteType: 'Tipul site-ului',
    landing: 'Landing page', corporate: 'Site business', redesign: 'Redesign site',
    unsure: 'Ajutați-mă să aleg', reply: 'Unde să îți răspundem?', replyPlaceholder: 'Email / Telegram / Instagram',
    replyAccount: 'Opțional — putem răspunde în contul tău',
    business: 'Site-ul sau rețelele sociale ale afacerii (opțional)', businessPlaceholder: 'Link către site sau profilul afacerii',
    businessHint: 'Dacă ai deja o afacere, lasă un link ca să o putem cunoaște.',
    commentPlaceholder: 'Cu ce te ocupi și ce ai dori să realizezi?',
    nextStep: 'Vom analiza cererea și te vom contacta folosind datele oferite.',
    accountNextStep: 'Vom analiza cererea și vom răspunde în contul tău sau la contactul oferit.',
    optional: 'Detalii opționale', estimate: 'Calculează o estimare', base: 'Exemplu de bază', applied: 'Estimare adăugată la cerere',
    next: 'Continuă: funcții suplimentare', back: 'Înapoi', apply: 'Adaugă estimarea la cerere',
    designs: 'Alege o direcție de design', allDesigns: 'Toate direcțiile de design',
  },
};

export const getInquiryUxCopy = (language) => copy[language] ?? copy.en;
