import type { ReactNode } from 'react';
import { modernDemos, modernText } from '../content/modernDemos';
import type { SiteLanguage } from '../content/siteLanguage';
import Art from './ModernDemoArt';

type Text = [string, string, string];
export const identityNotes: Record<string, { ribbon: Text; disciplines: string; stories: Text[] }> = {
  bento: { ribbon: ['One place. A clearer day.', 'Одне місце. Ясніший день.', 'Un singur loc. O zi mai clară.'], disciplines: 'NOTES / PLANNING / TEAMWORK', stories: [
    ['Save a thought, connect it to a project and return to it when you are ready. A quiet canvas keeps the idea in focus.', 'Збережіть думку, додайте її до проєкту й поверніться, коли будете готові. Спокійний простір допомагає зосередитися на ідеї.', 'Salvează un gând, leagă-l de un proiect și revino când ești pregătit. Un spațiu calm păstrează ideea în focus.'],
    ['Give each day a little structure. A weekly view brings priorities and small wins into one readable rhythm.', 'Додайте трохи структури кожному дню. Тижневий огляд об’єднує пріоритети й маленькі перемоги у зрозумілий ритм.', 'Oferă fiecărei zile puțină structură. Privirea săptămânală aduce prioritățile și micile reușite într-un ritm clar.'],
    ['Shared context makes collaboration lighter. Keep decisions, notes and the next step close to the people doing the work.', 'Спільний контекст полегшує співпрацю. Тримайте рішення, нотатки й наступний крок поруч із командою.', 'Contextul comun simplifică colaborarea. Păstrează deciziile, notițele și următorul pas aproape de echipă.'],
  ] },
  signal: { ribbon: ['A point of view. Made visible.', 'Власний погляд. Видимий усім.', 'Un punct de vedere. Făcut vizibil.'], disciplines: 'POSITIONING / IDENTITY / CAMPAIGNS', stories: [
    ['Start with what makes the brand different. Distil that idea into a position people can understand and a voice they recognise.', 'Почніть з особливості бренду. Перетворіть її на зрозуміле позиціювання та впізнаваний голос.', 'Începe cu ceea ce diferențiază brandul. Transformă ideea într-o poziție clară și o voce recognoscibilă.'],
    ['Type, colour and composition work as one system. From a small label to a full campaign, the identity keeps its own voice.', 'Шрифт, колір і композиція працюють як одна система. Від маленької етикетки до кампанії — айдентика зберігає власний голос.', 'Tipografia, culoarea și compoziția formează un sistem. De la o etichetă la o campanie, identitatea își păstrează vocea.'],
    ['A clear message deserves a confident stage. Build a campaign around one memorable idea, then adapt it to every touchpoint.', 'Чітке повідомлення потребує впевненої подачі. Побудуйте кампанію навколо однієї виразної ідеї та адаптуйте її до кожного контакту.', 'Un mesaj clar merită o prezentare convingătoare. Construiește campania în jurul unei idei memorabile și adapteaz-o fiecărui contact.'],
  ] },
  prism: { ribbon: ['Explore a different dimension.', 'Відкрийте інший вимір.', 'Explorează o altă dimensiune.'], disciplines: 'COLOUR / FORM / MOTION', stories: [
    ['Soft edges and pastel light create a calm, tactile mood. A direction for thoughtful products and a gentler digital experience.', 'М’які форми й пастельне світло створюють спокійний, відчутний настрій. Напрям для продуманих продуктів і делікатного цифрового досвіду.', 'Contururile moi și lumina pastelată creează o atmosferă calmă, tactilă. O direcție pentru produse atent gândite.'],
    ['Saturated colour and a strong silhouette bring energy to the foreground. Let one expressive object carry the composition.', 'Насичений колір і виразний силует додають енергії. Дозвольте одному яскравому об’єкту стати центром композиції.', 'Culoarea saturată și silueta puternică aduc energie. Lasă un singur obiect expresiv să susțină compoziția.'],
    ['An open form leaves room for discovery. Air, light and subtle motion give the experience a sense of possibility.', 'Відкрита форма залишає місце для відкриттів. Повітря, світло й делікатний рух створюють відчуття можливостей.', 'O formă deschisă lasă loc descoperirii. Aerul, lumina și mișcarea discretă sugerează noi posibilități.'],
  ] },
  cobalt: { ribbon: ['From strategy to a working system.', 'Від стратегії до дієвої системи.', 'De la strategie la un sistem funcțional.'], disciplines: 'STRATEGY / PLATFORMS / OPERATIONS', stories: [
    ['Map the challenge before choosing a solution. Connect business goals, user needs and a practical roadmap for the next stage.', 'Дослідіть виклик перед вибором рішення. Поєднайте цілі бізнесу, потреби користувачів і практичний план наступного етапу.', 'Analizează provocarea înainte de soluție. Conectează obiectivele afacerii, nevoile utilizatorilor și un plan practic.'],
    ['A strong platform makes complex work easier. Bring essential workflows together with clear interfaces and connected information.', 'Сильна платформа спрощує складну роботу. Об’єднайте ключові процеси через зрозумілі інтерфейси й узгоджену інформацію.', 'O platformă solidă simplifică munca complexă. Unește fluxurile esențiale prin interfețe clare și informații conectate.'],
    ['Build for the people who use the system every day. Clear ownership and small, continuous improvements keep the foundation useful.', 'Будуйте для тих, хто щодня працює із системою. Зрозуміла відповідальність і постійні покращення підтримують її цінність.', 'Construiește pentru cei care folosesc sistemul zilnic. Responsabilitățile clare și îmbunătățirile continue îi păstrează utilitatea.'],
  ] },
  maison: { ribbon: ['Material. Light. A sense of home.', 'Матеріал. Світло. Відчуття дому.', 'Material. Lumină. Sentimentul de acasă.'], disciplines: 'INTERIORS / ARCHITECTURE / OBJECTS', stories: [
    ['Natural light sets the pace of the room. Warm timber, tactile fabrics and a restrained palette make everyday moments feel considered.', 'Природне світло задає ритм кімнати. Тепла деревина, фактурні тканини й стримана палітра додають уваги щоденним моментам.', 'Lumina naturală dă ritmul camerei. Lemnul cald, țesăturile tactile și paleta discretă fac fiecare zi mai atentă.'],
    ['Architecture begins with its surroundings. Simple volumes and honest materials create a dialogue between the house and the landscape.', 'Архітектура починається з оточення. Прості об’єми й чесні матеріали створюють діалог будинку з ландшафтом.', 'Arhitectura începe cu împrejurimile. Volumele simple și materialele sincere creează un dialog cu peisajul.'],
    ['A quieter room is a collection of small decisions. Proportion, texture and the objects you keep close give the space its character.', 'Спокійна кімната — це низка маленьких рішень. Пропорції, фактура й близькі вам предмети формують характер простору.', 'O cameră calmă este o colecție de mici decizii. Proporția, textura și obiectele apropiate îi dau caracter.'],
  ] },
  haven: { ribbon: ['A place for the way you work.', 'Місце для вашого ритму роботи.', 'Un loc pentru felul tău de a lucra.'], disciplines: 'DESKS / TEAM ROOMS / MEETING SPACES', stories: [
    ['A desk, good light and space to think. Find a comfortable corner for independent work, with shared spaces when you need a change of pace.', 'Стіл, хороше світло й місце для думок. Знайдіть зручний куточок для самостійної роботи та спільні зони для зміни ритму.', 'Un birou, lumină bună și loc de gândit. Găsește un colț confortabil pentru lucru individual și spații comune pentru pauze.'],
    ['Keep the team together without losing room to focus. Private rooms sit alongside shared lounges and places for spontaneous conversations.', 'Об’єднайте команду, зберігаючи простір для фокусу. Приватні кімнати поруч зі спільними зонами й місцями для розмов.', 'Ține echipa împreună fără a pierde concentrarea. Camerele private completează saloanele comune și locurile de conversație.'],
    ['Make room for your next conversation. A welcoming setting for workshops, planning sessions and the ideas that happen around a table.', 'Знайдіть місце для наступної розмови. Затишний простір для воркшопів, планування й ідей, що народжуються за столом.', 'Fă loc următoarei conversații. Un cadru primitor pentru ateliere, planificare și ideile care apar în jurul unei mese.'],
  ] },
};
export const identityHeadings: Record<string, { about: Text; contact: Text; footer: Text }> = {
  bento: { about: ['Less switching. More doing.', 'Менше перемикань. Більше справ.', 'Mai puține schimbări. Mai mult progres.'], contact: ['Make room for your next idea.', 'Знайдіть місце для нової ідеї.', 'Fă loc următoarei idei.'], footer: ['A calmer kind of productive.', 'Спокійний ритм продуктивності.', 'Un ritm mai calm al productivității.'] },
  signal: { about: ['Clarity is a superpower.', 'Ясність — це сила.', 'Claritatea este o superputere.'], contact: ['Send a signal.', 'Дайте сигнал.', 'Trimite un semnal.'], footer: ['NO NOISE. JUST SIGNAL.', 'БЕЗ ШУМУ. ТІЛЬКИ СИГНАЛ.', 'FĂRĂ ZGOMOT. DOAR SEMNAL.'] },
  prism: { about: ['One spark. Infinite directions.', 'Одна іскра. Безліч напрямів.', 'O scânteie. Direcții infinite.'], contact: ['What colour is your next idea?', 'Якого кольору ваша наступна ідея?', 'Ce culoare are următoarea ta idee?'], footer: ['There is more than one way to shine.', 'Сяяти можна по-різному.', 'Există mai multe feluri de a străluci.'] },
  cobalt: { about: ['A system for moving forward.', 'Система для руху вперед.', 'Un sistem pentru a avansa.'], contact: ['Define your next step.', 'Визначте наступний крок.', 'Definește următorul pas.'], footer: ['CLEAR THINKING. CONNECTED SYSTEMS.', 'ЧІТКЕ МИСЛЕННЯ. ПОЄДНАНІ СИСТЕМИ.', 'GÂNDIRE CLARĂ. SISTEME CONECTATE.'] },
  maison: { about: ['Designed around your life.', 'Дизайн навколо вашого життя.', 'Design în jurul vieții tale.'], contact: ['Tell us about your place.', 'Розкажіть про ваш простір.', 'Spune-ne despre spațiul tău.'], footer: ['A quieter kind of beautiful.', 'Спокійна краса щодня.', 'O frumusețe mai discretă.'] },
  haven: { about: ['A good day starts here.', 'Хороший день починається тут.', 'O zi bună începe aici.'], contact: ['Find your place at Haven.', 'Знайдіть своє місце в Haven.', 'Găsește-ți locul la Haven.'], footer: ['GOOD SPACE. GOOD COMPANY.', 'ГАРНИЙ ПРОСТІР. ГАРНЕ ТОВАРИСТВО.', 'UN SPAȚIU BUN. O COMPANIE BUNĂ.'] },
};
type Props = { design: string; data: typeof modernDemos[string]; language: SiteLanguage; inner: boolean; cta: ReactNode; details: string; active: number; onActive: (index: number) => void };
function Arrow() { return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>; }

export function ModernExplore({design,data,language,inner,cta,details,active,onActive}: Props) {
  const t = (text: Text) => modernText(text,language);
  const Heading = inner ? 'h1' : 'h2';
  const heading = <div className="mi-section-heading"><span className="ld-kicker">01 / {data.brand}</span><Heading>{t(data.section)}</Heading></div>;
  if (design === 'cobalt') return <section id="explore" className="ld-container ld-section mi-services" data-md-reveal>{heading}<div className="mi-services-grid"><div className="mi-service-list">{data.items.map((item,i)=><div key={i}><button className="mi-service-toggle" aria-expanded={active===i} aria-controls={`service-panel-${i}`} onClick={()=>onActive(i)}><span>0{i+1}</span><strong>{t(item.title)}</strong><Arrow/></button><div id={`service-panel-${i}`} hidden={active!==i} className="mi-service-body"><p>{t(item.text)}</p><p>{t(identityNotes[design].stories[i])}</p>{cta}</div></div>)}</div><div className="mi-service-visual"><Art design={design} variant={active}/><span className="ld-kicker">{t(data.items[active].title)}</span></div></div></section>;
  if (design === 'haven') return <section id="explore" className="ld-container ld-section mi-room-section" data-md-reveal>{heading}<div className="mi-room-tabs" role="group" aria-label={t(data.section)}>{data.items.map((item,i)=><button key={i} className={`ld-button${active!==i?' ld-secondary':''}`} aria-pressed={active===i} onClick={()=>onActive(i)}>{t(item.title)}</button>)}</div><div className="mi-room-preview"><Art design={design} variant={active}/><div className="mi-room-description" aria-live="polite"><span className="ld-kicker">0{active+1} / HAVEN</span><h3>{t(data.items[active].title)}</h3><p>{t(data.items[active].text)}</p>{cta}</div></div></section>;
  return <section id="explore" className={`ld-container ld-section mi-projects mi-projects-${design}`} data-md-reveal>{heading}<div className="mi-project-list">{data.items.map((item,i)=><article key={i} className="mi-project"><div className="mi-project-visual"><Art design={design} variant={i}/></div><div className="mi-project-copy"><span className="ld-kicker">0{i+1} / {design}</span><h3>{t(item.title)}</h3><p>{t(item.text)}</p><details><summary>{details}<Arrow/></summary><p>{t(identityNotes[design].stories[i])}</p>{cta}</details></div></article>)}</div></section>;
}

export function ModernAbout({design,data,language,inner,cta}: Props) {
  const t = (text: Text) => modernText(text,language);
  const Heading = inner ? 'h1' : 'h2';
  const values: Record<string, Text[]> = {
    bento: [['Collect','Збирайте','Adună'],['Connect','Поєднуйте','Conectează'],['Create','Творіть','Creează']],
    cobalt: [['Discover the challenge','Досліджуємо виклик','Analizăm provocarea'],['Build the foundation','Будуємо основу','Construim fundația'],['Keep improving','Продовжуємо розвиток','Continuăm progresul']],
    haven: [['Natural light','Природне світло','Lumină naturală'],['Room to focus','Місце для фокусу','Loc pentru concentrare'],['People to connect with','Люди поруч','Oameni aproape']],
  };
  return <section id="approach" className={`mi-about mi-about-${design}`} data-md-reveal><div className="ld-container"><span className="ld-kicker">02 / {data.brand}</span><div className="mi-about-content">{design==='maison' && <div className="mi-about-photo"><Art design={design} variant={2}/></div>}<div className="mi-about-statement"><Heading>{t(identityHeadings[design].about)}</Heading><p>{t(data.about)}</p>{cta}</div>{design==='cobalt' && <div className="mi-timeline">{values.cobalt.map((value,i)=><div key={i}><span>0{i+1}</span><h3>{t(value)}</h3><p>{t(data.items[i].text)}</p></div>)}</div>}{design==='bento' && <div className="mi-step-stack">{values.bento.map((value,i)=><div key={i}><b>0{i+1}</b><div><h3>{t(value)}</h3><p>{t(data.items[i].text)}</p></div></div>)}</div>}</div>{design==='haven' && <div className="mi-amenities">{values.haven.map((value,i)=><div key={i}><span>0{i+1}</span><h3>{t(value)}</h3><p>{t(data.items[i].text)}</p></div>)}</div>}{design==='prism' && <div className="mi-spectrum" aria-hidden="true"><span/><span/><span/><span/><span/></div>}</div></section>;
}

export function ModernJournal({design,data,language,inner,cta,details}: Props) {
  const t = (text: Text) => modernText(text,language);
  const Heading = inner ? 'h1' : 'h2';
  const titles: Record<string,Text> = { cobalt:['Ideas for a clearer tomorrow.', 'Ідеї для зрозумілого завтра.', 'Idei pentru un viitor mai clar.'], maison:['Notes on living well.', 'Нотатки про гармонійне життя.', 'Notițe despre o viață armonioasă.'], haven:['From our community.', 'Історії нашої спільноти.', 'Din comunitatea noastră.'] };
  return <section id="questions" className={`ld-container ld-section mi-journal mi-journal-${design}`} data-md-reveal><div className="mi-section-heading"><span className="ld-kicker">03 / JOURNAL</span><Heading>{t(titles[design])}</Heading></div><div className="mi-journal-list">{data.items.map((item,i)=><article key={i}>{design!=='cobalt' && <div className="mi-journal-image"><Art design={design} variant={i}/></div>}<div><span className="ld-kicker">0{i+1} / {design==='cobalt'?'INSIGHT':'STORY'}</span><h3>{t(item.title)}</h3><details><summary>{details}<Arrow/></summary><p>{t(identityNotes[design].stories[i])}</p>{cta}</details></div></article>)}</div></section>;
}
