import { useId } from 'react';

export default function ModernDemoArt({ design, variant = 0 }: { design: string; variant?: number }) {
  const artId = useId().replace(/:/g, '');
  if (design === 'haven') return <div className="md-haven-photo"><img className="md-photo" src={['/images/business-demos/office.webp', '/images/business-demos/interior.webp', '/images/business-demos/meeting.webp'][variant]} alt=""/><span className="md-haven-caption">HAVEN / SPACE 0{variant + 1}</span></div>;
  if (design === 'prism') return <div className={`md-prism-art md-prism-mood-${variant}`} role="img" aria-label={['Soft gradient sculpture', 'Bold gradient sculpture', 'Open gradient sculpture'][variant]}><div className="md-prism-art-top"><span>PRISM / COLOUR STUDY</span><span>0{variant + 1}</span></div><svg viewBox="0 0 500 500" fill="none" aria-hidden="true"><defs><linearGradient id={`prism-${artId}`} x1="80" y1="70" x2="440" y2="440" gradientUnits="userSpaceOnUse"><stop stopColor="var(--prism-a)"/><stop offset=".5" stopColor="var(--prism-b)"/><stop offset="1" stopColor="var(--prism-c)"/></linearGradient><filter id={`depth-${artId}`} x="-40%" y="-40%" width="180%" height="180%"><feDropShadow dx="0" dy="14" stdDeviation="12" floodColor="var(--prism-b)" floodOpacity=".28"/></filter></defs><g className="md-prism-sculpture" filter={`url(#depth-${artId})`}><path d={['M140 155c0-110 220-100 220 0 0 75-220 110-220 190 0 100 220 90 220 0', 'M155 135c-80 50-80 180 0 230 95 60 250-25 205-130-40-95-205-40-205-100Z', 'M250 115c-150 0-190 235-65 270 95 27 205-30 170-120-25-65-160-60-105-150Z'][variant]} stroke={`url(#prism-${artId})`} strokeWidth="92" strokeLinecap="round"/><path d="M80 430h340" stroke="var(--ld-line)" strokeWidth="1"/></g></svg><div className="md-prism-art-bottom"><span>FORM / FEELING / POSSIBILITY</span><span className="md-prism-swatches" aria-hidden="true"><i/><i/><i/></span></div></div>;
  if (design === 'maison') return <img className="md-photo" src={['/images/business-demos/interior.webp', '/images/business-demos/house.webp', '/images/business-demos/room.webp'][variant]} alt=""/>;
  if (design === 'bento') return <div className="md-workspace" role="img" aria-label="Fictional workspace preview"><div className="md-workspace-top"><strong>bento / your space</strong><span>01—03</span></div><div className="md-bento-grid"><div className="md-note"><span>THE BIG PICTURE</span><strong>{['Make room\nfor good ideas.', 'One week.\nA clear direction.', 'Better work,\ntogether.'][variant]}</strong><svg viewBox="0 0 120 120" aria-hidden="true"><path d="M60 10v100M10 60h100M25 25l70 70M25 95l70-70" stroke="currentColor" strokeWidth="12"/></svg></div><div className="md-progress"><span>PROJECT MOMENTUM</span><strong>{[84, 92, 100][variant]}<small>%</small></strong><div><i style={{width: `${[84,92,100][variant]}%`}}/></div><span>A little progress, every day.</span></div><div className="md-calendar"><span>YOUR WEEK, IN FOCUS</span><div>{['M','T','W','T','F'].map((day,i) => <span key={i} className={i === variant + 1 ? 'is-current' : ''}>{day}<b>{12+i}</b></span>)}</div></div><div className="md-team"><span>GOOD COMPANY</span><div><b>AL</b><b>MK</b><b>JS</b><span>+ you</span></div></div></div></div>;
  if (design === 'signal') return <div className={`md-poster md-poster-${variant}`} role="img" aria-label="Original typographic brand poster"><span>DESIGNED TO MAKE A DIFFERENCE / 0{variant+1}</span><strong>{['Aa', '↗', '01'][variant]}</strong><div><b>SIGNAL®</b><span>CLARITY IS A SUPERPOWER.</span></div></div>;
  return <div className="md-system" role="img" aria-label="Connected digital system illustration"><div className="md-system-heading"><span>SYSTEM / 0{variant+1}</span><span>CONNECTED</span></div><svg viewBox="0 0 500 400" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1"><path d="M90 200h320M250 50v300M90 80l320 240M90 320 410 80"/><circle cx="250" cy="200" r="145"/><circle cx="250" cy="200" r="95"/><circle cx="250" cy="200" r="44"/></g><g fill="currentColor"><rect x="73" y="183" width="34" height="34" rx="8"/><rect x="393" y="183" width="34" height="34" rx="8"/><circle cx="250" cy="55" r="12"/><circle cx="250" cy="345" r="12"/></g><path d="m232 200 12 12 25-25" stroke="currentColor" strokeWidth="4"/></svg><div className="md-system-bottom"><strong>One connected foundation.</strong><span>STRATEGY → SYSTEMS → PEOPLE</span></div></div>;
}

