import type { UiCopy } from './types';

const copy: UiCopy = {
    cancellation: {
      action: 'Cancel brief', title: 'Cancel this brief?',
      description: 'The studio will see the brief as cancelled. The brief and its conversation will be permanently deleted 14 days after cancellation.',
      confirm: 'Cancel brief', processing: 'Cancelling…',
      error: 'Unable to cancel this brief. It may already be completed. Refresh the page and try again.',
      notice: 'This brief is cancelled and will be permanently deleted 14 days after cancellation.',
    },
    common: {
      nav: { solutions: 'Solutions', services: 'Services', cases: 'Cases', process: 'How We Work', about: 'About', contact: 'Contact' },
      discussProject: 'Discuss Project',
      homeMetaDescription: 'We build high-converting landing pages, functional business websites, modern website redesigns, and high-ROI ad campaigns.',
      projectBrief: 'Project Brief',
      projectBriefDescription: 'Tell I&I Studio about your project.',
      account: 'Account',
      availableLanguages: 'Available languages',
      toggleMenu: 'Toggle menu',
      enableLightTheme: 'Enable light theme',
      enableDarkTheme: 'Enable dark theme',
      signOut: 'Sign out',
      closeDialog: 'Close dialog',
      close: 'Close',
      cancel: 'Cancel',
      saveName: 'Save name',
      saving: 'Saving…',
      deleteAccount: 'Delete account',
      deleting: 'Deleting…',
      deletePermanently: 'Delete permanently',
    },
    auth: {
      pageSignIn: 'Sign in',
      pageCreateAccount: 'Create account',
      privateWorkspace: 'PRIVATE WORKSPACE',
      welcomeBack: 'Welcome back',
      createYourAccount: 'Create your account',
      signInDescription: 'Sign in with Google to access your personal workspace.',
      createAccountDescription: 'Register with Google to send your project brief and access your workspace.',
      inquiryRequiresAuth: 'Create or sign in to your account first. Your project brief will be ready when you return.',
      continueWithGoogle: 'Continue with Google',
      noPasswordNote: 'No password required. A new Google account is registered automatically.',
    },
    admin: {
      area: 'ADMIN AREA',
      workspace: 'Workspace control',
      accessPrefix: 'Admin access is active for',
      profile: 'Profile',
      openSite: 'Open site',
      sections: 'Admin sections',
      projectBriefs: 'Project briefs',
      registeredUsers: 'Registered users',
      workQueue: 'WORK QUEUE',
      people: 'PEOPLE',
      total: 'total',
      noProjectBriefs: 'No project briefs yet',
      newTasks: 'New tasks sent through the project form will appear here.',
      contact: 'Social networks',
      budget: 'Budget',
      client: 'Client',
      date: 'Date',
      description: 'Description',
      briefDetails: 'Project brief details',
      noDescription: 'No description provided.',
      noUsers: 'No users registered yet',
      unnamedUser: 'Unnamed user',
      registered: 'Registered',
      statuses: {
        new: 'Awaiting review',
        ready_to_start: 'Ready to start',
        in_progress: 'In progress',
        completed: 'Completed',
        cancelled: 'Cancelled',
      },
    },
    account: {
      pageTitle: 'Account',
      personalWorkspace: 'PERSONAL WORKSPACE',
      projectHistory: 'PROJECT HISTORY',
      myProjectBriefs: 'My project briefs',
      openEveryTask: 'Open every task you have sent to I&I Studio from this account.',
      viewAllBriefs: 'View all briefs',
      submittedBriefs: 'Submitted briefs',
      allTasks: 'All tasks you have sent to I&I Studio from this account.',
      backToAccount: 'Back to account',
      startNewBrief: 'Start new brief',
      noProjectBriefs: 'No project briefs yet',
      noProjectBriefsDescription: 'Your submitted tasks will appear here after you send the project form.',
      profileUpdated: 'Profile name updated.',
      accountLabel: 'ACCOUNT',
      workspaceTitle: 'Your workspace is ready.',
      workspaceDescription: 'Use this space to keep your project brief, conversations and next steps connected to your account.',
      profileLabel: 'PROFILE',
      profileTitle: 'Profile',
      name: 'Name',
      email: 'Email',
      signIn: 'Sign-in',
      google: 'Google',
      editName: 'Edit name',
      adminPanel: 'Admin panel',
      adminPanelDescription: 'Manage the studio workspace and upcoming administrative tools from here.',
      accountControl: 'ACCOUNT CONTROL',
      leaveStudio: 'Leave I&I Studio',
      leaveStudioDescription: 'Sign out on this device or permanently remove your workspace and account data.',
      changeName: 'Change your name',
      changeNameDescription: 'Choose the name that should appear in your personal workspace.',
      signOutTitle: 'Sign out?',
      signOutDescription: 'You can sign in again with Google whenever you want to return to your workspace.',
      signingOut: 'Signing out…',
      deleteTitle: 'Delete account?',
      deleteDescription: 'This permanently removes your workspace and account data. This action cannot be undone.',
      deleteConfirmationLabel: 'Type DELETE to confirm',
      deleteConfirmationPlaceholder: 'DELETE',
      deleteConfirmationError: 'Type DELETE to confirm.',
    },
    chat: {
      title: 'Project chat',
      today: 'Today',
      yesterday: 'Yesterday',
      dayBeforeYesterday: 'The day before yesterday',
      sent: 'Sent',
      read: 'Read',
      imageLimit: 'Attach up to 6 photos per message.',
      newMessages: 'New messages',
      adminInChat: 'Administrator in chat',
      clientInChat: 'Client in chat',
      adminAway: 'Administrator not in chat',
      clientAway: 'Client not in chat',
      unreadMessages: 'Unread messages',
      adminTyping: 'Administrator is typing',
      clientTyping: 'Client is typing',
      openChat: 'Open chat',
      studio: 'I&I Studio',
      empty: 'No messages yet. Start the conversation.',
      loading: 'Loading conversation…',
      loadError: 'We couldn’t load this conversation.',
      placeholder: 'Write a message…',
      addImage: 'Add image',
      messageActions: 'Message actions',
      editMessage: 'Edit message',
      deleteMessage: 'Delete message',
      deleteMessageConfirmation: 'Delete this message?',
      edited: 'Edited',
      editingMessage: 'Editing message',
      saveMessage: 'Save changes',
      actionError: 'Could not update the message. Please try again.',
      emptyEditError: 'The message cannot be empty.',
      removeImage: 'Remove image',
      imageAlt: 'Attached image',
      imageError: 'Choose a JPG, PNG, GIF, or WEBP image up to 5 MB.',
      send: 'Send',
      close: 'Close',
    },
    review: {
      write: 'Write a review',
      edit: 'Edit review',
      title: 'Share your experience',
      editTitle: 'Edit your review',
      description: 'Your feedback helps us make every project better.',
      rating: 'Your rating',
      ratingValue: '{rating} out of 5',
      clientReview: 'Client review',
      reviewPhotos: 'Review photos',
      comment: 'Your review',
      placeholder: 'Tell us what you think about working with us…',
      addPhoto: 'Add a photo',
      replacePhoto: 'Change photo',
      removePhoto: 'Remove photo',
      photoCount: '{count} of 6 photos',
      photoLimitError: 'You can add up to 6 photos.',
      save: 'Send review',
      update: 'Save changes',
      saving: 'Sending…',
      saved: 'Your review has been saved. You can edit it any time.',
      imageError: 'Choose a JPG, PNG, GIF, or WEBP image up to 5 MB.',
    },
    services: {
      landing: 'Landing Page',
      corporate: 'Business Website',
      redesign: 'Website Redesign',
      ads: 'Advertising',
      'meta-ads': 'Instagram & Facebook Ads',
      'tiktok-ads': 'TikTok Ads',
      marketplaces: 'Marketplaces',
      consultation: 'Consultation',
      other: 'Other',
    },
  };

export default copy;
