import type { UiCopy } from './types';

const copy: UiCopy = {
    cancellation: {
      action: 'Anulează brief-ul', title: 'Anulezi acest brief?',
      description: 'Studioul va vedea statusul „Anulat”. Brief-ul și conversația vor fi șterse definitiv la 14 zile după anulare.',
      confirm: 'Anulează brief-ul', processing: 'Se anulează…',
      error: 'Brief-ul nu a putut fi anulat. Este posibil să fie deja finalizat. Reîncarcă pagina și încearcă din nou.',
      notice: 'Acest brief este anulat și va fi șters definitiv la 14 zile după anulare.',
    },
    common: {
      nav: { solutions: 'Soluții', services: 'Servicii', cases: 'Studii de caz', process: 'Cum lucrăm', about: 'Despre noi', contact: 'Contact' },
      discussProject: 'Discută proiectul',
      homeMetaDescription: 'Construim landing pages cu conversie ridicată, site-uri funcționale, redesignuri moderne și campanii de publicitate eficiente.',
      projectBrief: 'Brief-ul proiectului',
      projectBriefDescription: 'Spune-i studioului I&I despre proiectul tău.',
      account: 'Cont',
      availableLanguages: 'Limbi disponibile',
      toggleMenu: 'Deschide meniul',
      enableLightTheme: 'Activează tema luminoasă',
      enableDarkTheme: 'Activează tema întunecată',
      signOut: 'Deconectare',
      closeDialog: 'Închide dialogul',
      close: 'Închide',
      cancel: 'Anulează',
      saveName: 'Salvează numele',
      saving: 'Se salvează…',
      deleteAccount: 'Șterge contul',
      deleting: 'Se șterge…',
      deletePermanently: 'Șterge definitiv',
    },
    auth: {
      pageSignIn: 'Autentificare',
      pageCreateAccount: 'Creează cont',
      privateWorkspace: 'SPAȚIU PERSONAL',
      welcomeBack: 'Bine ai revenit',
      createYourAccount: 'Creează-ți contul',
      signInDescription: 'Autentifică-te cu Google pentru a accesa spațiul personal.',
      createAccountDescription: 'Înregistrează-te cu Google pentru a trimite brief-ul proiectului și a accesa spațiul personal.',
      inquiryRequiresAuth: 'Creează mai întâi un cont sau autentifică-te. Brief-ul proiectului va fi gata când revii.',
      continueWithGoogle: 'Continuă cu Google',
      noPasswordNote: 'Nu este necesară o parolă. Un cont Google nou este înregistrat automat.',
    },
    admin: {
      area: 'PANOU ADMIN',
      workspace: 'Controlul spațiului de lucru',
      accessPrefix: 'Accesul de administrator este activ pentru',
      profile: 'Profil',
      openSite: 'Deschide site-ul',
      sections: 'Secțiuni admin',
      projectBriefs: 'Solicitări de proiect',
      registeredUsers: 'Utilizatori înregistrați',
      workQueue: 'COADA DE LUCRU',
      people: 'UTILIZATORI',
      total: 'în total',
      noProjectBriefs: 'Nu există solicitări încă',
      newTasks: 'Solicitările noi trimise prin formular vor apărea aici.',
      contact: 'Rețele sociale',
      budget: 'Buget',
      client: 'Client',
      date: 'Data',
      description: 'Descriere',
      briefDetails: 'Detalii solicitare',
      noDescription: 'Nu a fost furnizată nicio descriere.',
      noUsers: 'Nu există utilizatori înregistrați încă',
      unnamedUser: 'Utilizator fără nume',
      registered: 'Înregistrat',
      statuses: {
        new: 'În așteptarea verificării',
        ready_to_start: 'Gata de începere',
        in_progress: 'În lucru',
        completed: 'Finalizat',
        cancelled: 'Anulat',
      },
    },
    account: {
      pageTitle: 'Cont',
      personalWorkspace: 'SPAȚIU PERSONAL',
      projectHistory: 'ISTORICUL PROIECTELOR',
      myProjectBriefs: 'Solicitările mele',
      openEveryTask: 'Deschide toate solicitările trimise către I&I Studio din acest cont.',
      viewAllBriefs: 'Vezi toate solicitările',
      submittedBriefs: 'Solicitări trimise',
      allTasks: 'Toate solicitările trimise către I&I Studio din acest cont.',
      backToAccount: 'Înapoi la cont',
      startNewBrief: 'Solicitare nouă',
      noProjectBriefs: 'Nu există solicitări încă',
      noProjectBriefsDescription: 'Solicitările trimise vor apărea aici după expedierea formularului.',
      profileUpdated: 'Numele profilului a fost actualizat.',
      accountLabel: 'CONT',
      workspaceTitle: 'Spațiul tău este pregătit.',
      workspaceDescription: 'Păstrează aici brief-ul proiectului, conversațiile și pașii următori conectați la contul tău.',
      profileLabel: 'PROFIL',
      profileTitle: 'Profil',
      name: 'Nume',
      email: 'Email',
      signIn: 'Autentificare',
      google: 'Google',
      editName: 'Editează numele',
      adminPanel: 'Panou admin',
      adminPanelDescription: 'Gestionează spațiul studioului și viitoarele instrumente administrative de aici.',
      accountControl: 'CONTROLUL CONTULUI',
      leaveStudio: 'Părăsește I&I Studio',
      leaveStudioDescription: 'Deconectează-te de pe acest dispozitiv sau elimină definitiv spațiul și datele contului.',
      changeName: 'Schimbă-ți numele',
      changeNameDescription: 'Alege numele care va apărea în spațiul tău personal.',
      signOutTitle: 'Deconectare?',
      signOutDescription: 'Te poți autentifica din nou cu Google oricând vrei să revii în spațiul tău.',
      signingOut: 'Se deconectează…',
      deleteTitle: 'Ștergi contul?',
      deleteDescription: 'Acest lucru elimină definitiv spațiul și datele contului. Acțiunea nu poate fi anulată.',
      deleteConfirmationLabel: 'Tastează DELETE pentru confirmare',
      deleteConfirmationPlaceholder: 'DELETE',
      deleteConfirmationError: 'Tastează DELETE pentru confirmare.',
    },
    chat: {
      title: 'Chatul proiectului',
      today: 'Astăzi',
      yesterday: 'Ieri',
      dayBeforeYesterday: 'Alaltăieri',
      sent: 'Trimis',
      read: 'Citit',
      imageLimit: 'Atașați până la 6 fotografii per mesaj.',
      newMessages: 'Mesaje noi',
      adminInChat: 'Administratorul este în chat',
      clientInChat: 'Clientul este în chat',
      adminAway: 'Administratorul nu este în chat',
      clientAway: 'Clientul nu este în chat',
      unreadMessages: 'Mesaje necitite',
      adminTyping: 'Administratorul scrie',
      clientTyping: 'Clientul scrie',
      openChat: 'Deschide chatul',
      studio: 'I&I Studio',
      empty: 'Nu există mesaje. Începe conversația.',
      loading: 'Se încarcă conversația…',
      loadError: 'Conversația nu a putut fi încărcată.',
      placeholder: 'Scrie un mesaj…',
      addImage: 'Adaugă o imagine',
      messageActions: 'Acțiuni pentru mesaj',
      editMessage: 'Editează mesajul',
      deleteMessage: 'Șterge mesajul',
      deleteMessageConfirmation: 'Ștergi acest mesaj?',
      edited: 'Modificat',
      editingMessage: 'Editare mesaj',
      saveMessage: 'Salvează modificările',
      actionError: 'Mesajul nu a putut fi actualizat. Încearcă din nou.',
      emptyEditError: 'Mesajul nu poate fi gol.',
      removeImage: 'Elimină imaginea',
      imageAlt: 'Imagine atașată',
      imageError: 'Alege o imagine JPG, PNG, GIF sau WEBP de maximum 5 MB.',
      send: 'Trimite',
      close: 'Închide',
    },
    review: {
      write: 'Scrie o recenzie',
      edit: 'Editează recenzia',
      title: 'Spune-ne cum a fost',
      editTitle: 'Editează recenzia',
      description: 'Părerea ta ne ajută să îmbunătățim fiecare proiect.',
      rating: 'Evaluarea ta',
      ratingValue: '{rating} din 5',
      clientReview: 'Recenzia clientului',
      reviewPhotos: 'Fotografii din recenzie',
      comment: 'Recenzia ta',
      placeholder: 'Povestește-ne cum a fost colaborarea…',
      addPhoto: 'Adaugă o fotografie',
      replacePhoto: 'Schimbă fotografia',
      removePhoto: 'Elimină fotografia',
      photoCount: '{count} din 6 fotografii',
      photoLimitError: 'Poți adăuga cel mult 6 fotografii.',
      save: 'Trimite recenzia',
      update: 'Salvează modificările',
      saving: 'Se trimite…',
      saved: 'Recenzia a fost salvată. O poți modifica oricând.',
      imageError: 'Alege o imagine JPG, PNG, GIF sau WEBP de maximum 5 MB.',
    },
    services: {
      landing: 'Landing page',
      corporate: 'Site de companie',
      redesign: 'Redesign site',
      ads: 'Publicitate',
      'meta-ads': 'Instagram & Facebook Ads',
      'tiktok-ads': 'TikTok Ads',
      marketplaces: 'Marketplace-uri',
      consultation: 'Consultație',
      other: 'Altele',
    },
  };

export default copy;
