type CommonCopy = {
  nav: {
    solutions: string;
    services: string;
    cases: string;
    process: string;
    about: string;
    contact: string;
  };
  discussProject: string;
  homeMetaDescription: string;
  projectBrief: string;
  projectBriefDescription: string;
  account: string;
  availableLanguages: string;
  toggleMenu: string;
  enableLightTheme: string;
  enableDarkTheme: string;
  signOut: string;
  closeDialog: string;
  close: string;
  cancel: string;
  saveName: string;
  saving: string;
  deleteAccount: string;
  deleting: string;
  deletePermanently: string;
};

type AuthCopy = {
  pageSignIn: string;
  pageCreateAccount: string;
  privateWorkspace: string;
  welcomeBack: string;
  createYourAccount: string;
  signInDescription: string;
  createAccountDescription: string;
  inquiryRequiresAuth: string;
  continueWithGoogle: string;
  noPasswordNote: string;
};

type AdminCopy = {
  area: string;
  workspace: string;
  accessPrefix: string;
  profile: string;
  openSite: string;
  sections: string;
  projectBriefs: string;
  registeredUsers: string;
  workQueue: string;
  people: string;
  total: string;
  noProjectBriefs: string;
  newTasks: string;
  contact: string;
  budget: string;
  client: string;
  date: string;
  description: string;
  briefDetails: string;
  noDescription: string;
  noUsers: string;
  unnamedUser: string;
  registered: string;
  statuses: Record<string, string>;
};

type AccountCopy = {
  pageTitle: string;
  personalWorkspace: string;
  projectHistory: string;
  myProjectBriefs: string;
  openEveryTask: string;
  viewAllBriefs: string;
  submittedBriefs: string;
  allTasks: string;
  backToAccount: string;
  startNewBrief: string;
  noProjectBriefs: string;
  noProjectBriefsDescription: string;
  profileUpdated: string;
  accountLabel: string;
  workspaceTitle: string;
  workspaceDescription: string;
  profileLabel: string;
  profileTitle: string;
  name: string;
  email: string;
  signIn: string;
  google: string;
  editName: string;
  adminPanel: string;
  adminPanelDescription: string;
  accountControl: string;
  leaveStudio: string;
  leaveStudioDescription: string;
  changeName: string;
  changeNameDescription: string;
  signOutTitle: string;
  signOutDescription: string;
  signingOut: string;
  deleteTitle: string;
  deleteDescription: string;
  deleteConfirmationLabel: string;
  deleteConfirmationPlaceholder: string;
  deleteConfirmationError: string;
};

type ChatCopy = {
  unreadMessages: string;
  messageActions: string;
  editMessage: string;
  deleteMessage: string;
  deleteMessageConfirmation: string;
  edited: string;
  editingMessage: string;
  saveMessage: string;
  actionError: string;
  emptyEditError: string;
  today: string;
  yesterday: string;
  dayBeforeYesterday: string;
  sent: string;
  read: string;
  imageLimit: string;
  adminInChat: string;
  clientInChat: string;
  adminAway: string;
  clientAway: string;
  adminTyping: string;
  clientTyping: string;
  newMessages: string;
  title: string;
  openChat: string;
  studio: string;
  empty: string;
  loading: string;
  loadError: string;
  placeholder: string;
  addImage: string;
  removeImage: string;
  imageAlt: string;
  imageError: string;
  send: string;
  close: string;
};

type ReviewCopy = {
  write: string;
  edit: string;
  title: string;
  editTitle: string;
  description: string;
  rating: string;
  ratingValue: string;
  clientReview: string;
  reviewPhotos: string;
  comment: string;
  placeholder: string;
  addPhoto: string;
  replacePhoto: string;
  removePhoto: string;
  photoCount: string;
  photoLimitError: string;
  save: string;
  update: string;
  saving: string;
  saved: string;
  imageError: string;
};

export type UiCopy = {
  cancellation: {
    action: string;
    title: string;
    description: string;
    confirm: string;
    processing: string;
    error: string;
    notice: string;
  };
  common: CommonCopy;
  auth: AuthCopy;
  admin: AdminCopy;
  account: AccountCopy;
  chat: ChatCopy;
  review: ReviewCopy;
  services: Record<string, string>;
};
