import type { UiCopy } from './types';

const copy: UiCopy = {
    cancellation: {
      action: 'Скасувати бриф', title: 'Скасувати цей бриф?',
      description: 'Студія побачить статус «Скасовано». Бриф і листування буде остаточно видалено через 14 днів після скасування.',
      confirm: 'Скасувати бриф', processing: 'Скасування…',
      error: 'Не вдалося скасувати бриф. Можливо, його вже завершено. Оновіть сторінку та спробуйте ще раз.',
      notice: 'Цей бриф скасовано. Його буде остаточно видалено через 14 днів після скасування.',
    },
    common: {
      nav: { solutions: 'Рішення', services: 'Послуги', cases: 'Кейси', process: 'Як ми працюємо', about: 'Про нас', contact: 'Контакти' },
      discussProject: 'Обговорити проєкт',
      homeMetaDescription: 'Ми створюємо конверсійні лендинги, функціональні сайти для бізнесу, сучасний редизайн і результативні рекламні кампанії.',
      projectBrief: 'Бриф проєкту',
      projectBriefDescription: 'Розкажіть I&I Studio про ваш проєкт.',
      account: 'Акаунт',
      availableLanguages: 'Доступні мови',
      toggleMenu: 'Відкрити меню',
      enableLightTheme: 'Увімкнути світлу тему',
      enableDarkTheme: 'Увімкнути темну тему',
      signOut: 'Вийти',
      closeDialog: 'Закрити діалогове вікно',
      close: 'Закрити',
      cancel: 'Скасувати',
      saveName: 'Зберегти імʼя',
      saving: 'Збереження…',
      deleteAccount: 'Видалити акаунт',
      deleting: 'Видалення…',
      deletePermanently: 'Видалити назавжди',
    },
    auth: {
      pageSignIn: 'Увійти',
      pageCreateAccount: 'Створити акаунт',
      privateWorkspace: 'ОСОБИСТИЙ ПРОСТІР',
      welcomeBack: 'Раді вас бачити',
      createYourAccount: 'Створіть свій акаунт',
      signInDescription: 'Увійдіть через Google, щоб відкрити особистий простір.',
      createAccountDescription: 'Зареєструйтеся через Google, щоб надіслати бриф проєкту та відкрити свій простір.',
      inquiryRequiresAuth: 'Спочатку створіть акаунт або увійдіть. Після повернення ваш бриф проєкту буде готовий.',
      continueWithGoogle: 'Продовжити через Google',
      noPasswordNote: 'Пароль не потрібен. Новий акаунт Google зареєструється автоматично.',
    },
    admin: {
      area: 'АДМІН-ПАНЕЛЬ',
      workspace: 'Керування робочим простором',
      accessPrefix: 'Доступ адміністратора активний для',
      profile: 'Профіль',
      openSite: 'Відкрити сайт',
      sections: 'Розділи адмін-панелі',
      projectBriefs: 'Завдання проєкту',
      registeredUsers: 'Зареєстровані користувачі',
      workQueue: 'ЧЕРГА РОБОТИ',
      people: 'КОРИСТУВАЧІ',
      total: 'всього',
      noProjectBriefs: 'Завдань поки немає',
      newTasks: 'Нові завдання з форми проєкту зʼявляться тут.',
      contact: 'Соцмережі',
      budget: 'Бюджет',
      client: 'Клієнт',
      date: 'Дата',
      description: 'Опис',
      briefDetails: 'Деталі завдання',
      noDescription: 'Опис відсутній.',
      noUsers: 'Зареєстрованих користувачів поки немає',
      unnamedUser: 'Користувач без імені',
      registered: 'Зареєстровано',
      statuses: {
        new: 'Очікує перевірки',
        ready_to_start: 'Готово до старту',
        in_progress: 'У роботі',
        completed: 'Завершено',
        cancelled: 'Скасовано',
      },
    },
    account: {
      pageTitle: 'Акаунт',
      personalWorkspace: 'ОСОБИСТИЙ ПРОСТІР',
      projectHistory: 'ІСТОРІЯ ПРОЄКТІВ',
      myProjectBriefs: 'Мої завдання',
      openEveryTask: 'Відкрийте всі завдання, які ви надіслали I&I Studio з цього акаунта.',
      viewAllBriefs: 'Відкрити всі завдання',
      submittedBriefs: 'Надіслані завдання',
      allTasks: 'Усі завдання, які ви надіслали I&I Studio з цього акаунта.',
      backToAccount: 'До акаунта',
      startNewBrief: 'Нове завдання',
      noProjectBriefs: 'Завдань поки немає',
      noProjectBriefsDescription: 'Надіслані завдання зʼявляться тут після відправки форми.',
      profileUpdated: 'Імʼя профілю оновлено.',
      accountLabel: 'АКАУНТ',
      workspaceTitle: 'Ваш простір готовий.',
      workspaceDescription: 'Зберігайте тут бриф проєкту, листування та наступні кроки, повʼязані з вашим акаунтом.',
      profileLabel: 'ПРОФІЛЬ',
      profileTitle: 'Профіль',
      name: 'Імʼя',
      email: 'Email',
      signIn: 'Вхід',
      google: 'Google',
      editName: 'Змінити імʼя',
      adminPanel: 'Адмін-панель',
      adminPanelDescription: 'Керуйте робочим простором студії та майбутніми адміністративними інструментами.',
      accountControl: 'КЕРУВАННЯ АКАУНТОМ',
      leaveStudio: 'Вийти з I&I Studio',
      leaveStudioDescription: 'Вийдіть на цьому пристрої або назавжди видаліть свій простір і дані акаунта.',
      changeName: 'Змінити ваше імʼя',
      changeNameDescription: 'Оберіть імʼя, яке відображатиметься у вашому особистому просторі.',
      signOutTitle: 'Вийти?',
      signOutDescription: 'Ви зможете знову увійти через Google, коли захочете повернутися до свого простору.',
      signingOut: 'Вихід…',
      deleteTitle: 'Видалити акаунт?',
      deleteDescription: 'Це назавжди видалить ваш простір і дані акаунта. Дію неможливо скасувати.',
      deleteConfirmationLabel: 'Введіть DELETE для підтвердження',
      deleteConfirmationPlaceholder: 'DELETE',
      deleteConfirmationError: 'Введіть DELETE для підтвердження.',
    },
    chat: {
      title: 'Чат проєкту',
      today: 'Сьогодні',
      yesterday: 'Вчора',
      dayBeforeYesterday: 'Позавчора',
      sent: 'Надіслано',
      read: 'Прочитано',
      imageLimit: 'Додайте до 6 фото в одному повідомленні.',
      newMessages: 'Нові повідомлення',
      adminInChat: 'Адміністратор у чаті',
      clientInChat: 'Клієнт у чаті',
      adminAway: 'Адміністратор не в чаті',
      clientAway: 'Клієнт не в чаті',
      unreadMessages: 'Непрочитані повідомлення',
      adminTyping: 'Адміністратор друкує',
      clientTyping: 'Клієнт друкує',
      openChat: 'Відкрити чат',
      studio: 'I&I Studio',
      empty: 'Повідомлень ще немає. Почніть розмову.',
      loading: 'Завантаження чату…',
      loadError: 'Не вдалося завантажити цей чат.',
      placeholder: 'Напишіть повідомлення…',
      addImage: 'Додати зображення',
      messageActions: 'Дії з повідомленням',
      editMessage: 'Змінити повідомлення',
      deleteMessage: 'Видалити повідомлення',
      deleteMessageConfirmation: 'Видалити це повідомлення?',
      edited: 'Відредаговано',
      editingMessage: 'Редагування повідомлення',
      saveMessage: 'Зберегти зміни',
      actionError: 'Не вдалося змінити повідомлення. Спробуйте ще раз.',
      emptyEditError: 'Повідомлення не може бути порожнім.',
      removeImage: 'Видалити зображення',
      imageAlt: 'Прикріплене зображення',
      imageError: 'Оберіть зображення JPG, PNG, GIF або WEBP розміром до 5 МБ.',
      send: 'Надіслати',
      close: 'Закрити',
    },
    review: {
      write: 'Залишити відгук',
      edit: 'Змінити відгук',
      title: 'Поділіться враженнями',
      editTitle: 'Редагувати відгук',
      description: 'Ваш відгук допоможе нам ставати кращими з кожним проєктом.',
      rating: 'Ваша оцінка',
      ratingValue: '{rating} з 5',
      clientReview: 'Відгук клієнта',
      reviewPhotos: 'Фото до відгуку',
      comment: 'Ваш відгук',
      placeholder: 'Розкажіть про співпрацю з нами…',
      addPhoto: 'Додати фото',
      replacePhoto: 'Змінити фото',
      removePhoto: 'Видалити фото',
      photoCount: '{count} з 6 фото',
      photoLimitError: 'Можна додати не більше 6 фото.',
      save: 'Надіслати відгук',
      update: 'Зберегти зміни',
      saving: 'Надсилання…',
      saved: 'Відгук збережено. Ви можете змінити його будь-коли.',
      imageError: 'Оберіть зображення JPG, PNG, GIF або WEBP розміром до 5 МБ.',
    },
    services: {
      landing: 'Лендінг',
      corporate: 'Бізнес-сайт',
      redesign: 'Редизайн сайту',
      ads: 'Реклама',
      'meta-ads': 'Instagram & Facebook Ads',
      'tiktok-ads': 'TikTok Ads',
      marketplaces: 'Маркетплейси',
      consultation: 'Консультація',
      other: 'Інше',
    },
  };

export default copy;
